language: rust
rust:
   - stable
services:
   - docker
install:
   - docker pull emag3m/near-evm:build
before_script:
   - docker images
   - docker build --cache-from f2b8cab0294d --tag emag3m/near-evm:0.1.0 .
script:
   - docker run emag3m/near-evm:0.1.0 /bin/sh -c "cargo test --lib"
