language: rust
cache:
    directories:
        - $TRAVIS_BUILD_DIR/target
        - /home/travis/.cargo
rust:
  - nightly-2020-03-19
install:
  - rustup target add wasm32-unknown-unknownsudo
  - add-apt-repository ppa:ethereum/ethereum
  - apt-get update && apt-get install solc
before_script:
  - cargo build --target wasm32-unknown-unknown --release # ./build.sh needs target/wasm32-unknown-unknown/release/near_evm.wasm
  - cd src/tests && ./build.sh && cd ../.. && ./build.sh
script:
  - cargo test --lib
