language: rust
rust:
   - stable
services:
   - docker
install:
   - docker pull ethereum/solc:0.5.17-alpine
   - docker pull rust:1.43-buster
   - docker pull emag3m/near-evm:build
before_script:
   - docker images
   - docker build --cache-from emag3m/near-evm:build --tag emag3m/near-evm:0.1.0 .
script:
   - docker run emag3m/near-evm:0.1.0 /bin/sh -c "cargo test --lib"
