matrix:
    include:
      - language: rust
        rust: stable
        env:
          global:
            - SOLC_VERSION='v0.5.4'
            - SOLC_URL="https://github.com/ethereum/solidity/releases/download/$SOLC_VERSION/solc-static-linux"
        cache:
            directories:
                - ./target
                - /home/travis/.cargo
        install:
          - ./.travis/download_solc.sh
        before_script:
          - cd ../src/tests && ./build.sh solc && cd ../..
        script:
          - cargo test --lib

      - language: rust
        rust: stable
        before_install:
          - rustup target add wasm32-unknown-unknown --toolchain stable
        install:
          - cargo +stable build --target wasm32-unknown-unknown --release # ./build.sh needs target/wasm32-unknown-unknown/release/near_evm.wasm
        script:
          - ./build.sh
