[package]
name = "near-evm"
edition = "2018"
version = "0.1.0"
license = "GPL-3.0"
description = "EVM interpreter as a NEAR smart contract"
publish = false

[dependencies]
evm = { git = "https://github.com/paritytech/parity-ethereum" }
vm = { git = "https://github.com/paritytech/parity-ethereum" }
parity-bytes = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.3.2"
wasm-bindgen = "0.2"

[dev-dependencies]
lazy_static = "1.3"
ethabi = "8.0.0"
ethabi-contract = "8.0.0"
ethabi-derive = "8.0.0"
protobuf = "2.4"
near-jsonrpc = { git = "https://github.com/nearprotocol/nearcore" }
near-primitives = { git = "https://github.com/nearprotocol/nearcore" }
near-protos = { git = "https://github.com/nearprotocol/nearcore" }
near-client = { git = "https://github.com/nearprotocol/nearcore" } # for StatusResponse
actix = "0.8.2"
futures = "0.1.27"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
debug = false

